name: build exe

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: set python up
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: install the dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pywebview keyboard
    - name: build exe
      run: |
        pyinstaller --onefile --windowed app.py --icon=app.ico

    - name: upload to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist/app.exe
